[functions."sell"]
schedule = "*/10 * * * *"
[functions."large-buy"]
schedule = "*/15 * * * *"
[functions]
  node_bundler = "esbuild"
[build]
  functions = "netlify/functions/"
[dev]
  functions = "netlify/functions"